/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build"
#define EXEC_PREFIX "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build"
#define BINDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/bin"
#define SBINDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/sbin"
#define LIBEXECDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/libexec"
#define DATAROOTDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share"
#define DATADIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share"
#define SYSCONFDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/etc"
#define SHAREDSTATEDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/com"
#define LOCALSTATEDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/var"
#define RUNSTATEDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/var/run"
#define INCLUDEDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share/doc/coreutils"
#define INFODIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share/info"
#define HTMLDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share/doc/coreutils"
#define DVIDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share/doc/coreutils"
#define PDFDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share/doc/coreutils"
#define PSDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share/doc/coreutils"
#define LIBDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/lib"
#define LISPDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share/emacs/site-lisp"
#define LOCALEDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share/locale"
#define MANDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share/man"
#define PKGDATADIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/share/coreutils"
#define PKGINCLUDEDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/include/coreutils"
#define PKGLIBDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/lib/coreutils"
#define PKGLIBEXECDIR "/home/eric/Projets/nulix/coreutils/coreutils-8.32/../coreutils-8.32-build/libexec/coreutils"
