# Memory
megs: 512

# BIOS
romimage: file=$BXSHARE/BIOS-bochs-latest
vgaromimage: file=$BXSHARE/VGABIOS-lgpl-latest

# Boot order
boot: cdrom, disk

# Disks
ata0-master: type=disk, path="hda.img", mode=flat
ata1-master: type=cdrom, path="nulix.iso", status=inserted

# Serial
com1: enabled=1, mode=file, dev=bochs.log
