#!/bin/bash

# load french key map
loadkeys /usr/share/keymaps/i386/azerty/fr-latin1.map.gz

# configure network
ifconfig eth0 192.168.1.100 netmask 255.255.255.0 up
route add -net 192.168.1.0 netmask 255.255.255.0 gw 192.168.1.1 eth0
