#!/bin/sh

DAEMON="network"

printf 'Starting %s: ' "$DAEMON"

# set ip
ifconfig eth0 192.168.1.100 netmask 255.255.255.0 up
status=$?

# set local route
if [ "$status" -eq 0 ]; then
	route add -net 192.168.1.0 netmask 255.255.255.0 dev eth0
	status=$?
fi

# set default gateway
if [ "$status" -eq 0 ]; then
	route add default gw 192.168.1.1 eth0
	status=$?
fi

if [ "$status" -eq 0 ]; then
	echo "OK"
else
	echo "FAIL"
fi
