#!/bin/sh

DAEMON="network"

printf 'Starting %s: ' "$DAEMON"

# configure loopback
ifconfig lo up								\
	&& route add -host 127.0.0.1 dev lo

# configure eth0
ifconfig eth0 192.168.1.100 netmask 255.255.255.0 up			\
	&& route add -net 192.168.1.0 netmask 255.255.255.0 dev eth0	\
	&& route add default gw 192.168.1.1 eth0

status=$?
if [ "$status" -eq 0 ]; then
	echo "OK"
else
	echo "FAIL"
fi
